# Background and foreground colors
background = #0F1518
foreground = #ffffff

# Standard colors
palette = 0=#0F1518
palette = 1=#b17c77
palette = 2=#5EC7C3
palette = 3=#bb9b8c
palette = 4=#91939C
palette = 5=#b4b1b3
palette = 6=#9dced8
palette = 7=#F7F9FB

# Bright colors
palette = 8=#788b94
palette = 9=#d4b3b0
palette = 10=#9fe2df
palette = 11=#decdc5
palette = 12=#c1c2c8
palette = 13=#e1e0e1
palette = 14=#deeff3
palette = 15=#ffffff
