background            #0F1518
foreground            #ffffff

# black
color0  #0F1518
color8  #788b94

# red
color1  #b17c77
color9  #d4b3b0

# green
color2  #5EC7C3
color10 #9fe2df

# yellow
color3  #bb9b8c
color11 #decdc5

# blue
color4  #91939C
color12 #c1c2c8

# magenta
color5  #b4b1b3
color13 #e1e0e1

#cyan
color6  #9dced8
color14 #deeff3

#white
color7  #F7F9FB
color15 #ffffff


