# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E0E0BA
background         #1B1C1A
cursor             #7C7F67

active_tab_foreground     #1B1C1A
active_tab_background     #E0E0BA
inactive_tab_foreground   #E0E0BA
inactive_tab_background   #1B1C1A

active_border_color   #E0E0BA
inactive_border_color #1B1C1A
bell_border_color     #12160F

color0      #414240
color1		#12160F
color2		#12160F
color3		#12160F
color4		#171B12
color5		#484D1C
color6		#7D7D2C
color7		#CBCB95
color8		#8E8E68
color9		#181D14
color10		#181D14
color11		#181D14
color12		#1F2517
color13		#606626
color14		#A7A73B
color15		#CBCB95
