# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R

unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix


set-window-option -g mode-keys vi

bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded"
bind-key -T copy-mode-vi J send-keys -X page-up
bind-key -T copy-mode-vi K send-keys -X page-down

set-option -g mouse on

bind S command-prompt -p 'New session name:' 'new-session -s "%%"'


bind -n M-h resize-pane -L 2    # Alt+h = resize left 2 cells
bind -n M-j resize-pane -D 2    # Alt+j = resize down 2 cells
bind -n M-k resize-pane -U 2    # Alt+k = resize up 2 cells
bind -n M-l resize-pane -R 2    # Alt+l = resize right 2 cells

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'
