# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc,alacritty:Tc,wezterm:Tc,*:RGB"

# Prefix
unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix


set-window-option -g mode-keys vi

bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded"

bind-key -T copy-mode-vi J send-keys -X page-up
bind-key -T copy-mode-vi K send-keys -X page-down

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Faster command delay (very noticeable when using vim/neovim)
set -sg escape-time 10
set -g renumber-windows on

# Better clipboard integration (works with most terminals)
set -g set-clipboard on

# Start window/pane indexing at 1 (more natural)
set -g base-index 1
setw -g pane-base-index 1

# =============================================
#  Splits — natural and memorable
# =============================================

# bind | split-window -h -c "#{pane_current_path}"
# bind - split-window -v -c "#{pane_current_path}"
set -g status-position top

# Left: session name (blue background when prefix pressed)
setw -g window-status-current-format " #I:#W#F "
setw -g window-status-format " #I:#W#F "
# Make status bar thin & clean

# Swap windows left/right
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Enable mouse support
set-option -g mouse on

bind S command-prompt -p 'New session name:' 'new-session -s "%%"'


bind -n M-h resize-pane -L 2    # Alt+h = resize left 2 cells
bind -n M-j resize-pane -D 2    # Alt+j = resize down 2 cells
bind -n M-k resize-pane -U 2    # Alt+k = resize up 2 cells
bind -n M-l resize-pane -R 2    # Alt+l = resize right 2 cells


# open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"



# Run the package manager
run '~/.tmux/plugins/tpm/tpm'


set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_number_position    "right"
set -g @catppuccin_window_text               "#W"
set -g @catppuccin_window_default_fill       "number"
set -g @catppuccin_window_default_text       "#W"
set -g @catppuccin_window_current_fill       "number"
set -g @catppuccin_window_current_text       "#W"
setw -g window-status-style "fg=colour245"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Tmux Package Manager
set -g @plugin 'tmux-plugins/tpm'

# Navigate with C-hjkl
set -g @plugin 'christoomey/vim-tmux-navigator'
