cursor #e0e2e8
cursor_text_color #c2c7cf

foreground            #e0e2e8
background            #101418
selection_foreground  #243240
selection_background  #bac8da
url_color             #9dcbfc

color0   #101418
color1   #ff729c
color2   #7efc8e
color3   #fff772
color4   #83b7ef
color5   #244b74
color6   #9dcbfc
color7   #eff7ff
color8   #3f4347
color9   #ff9fbb
color10  #a5ffb1
color11  #fffaa5
color12  #add4ff
color13  #bbdcff
color14  #d3e8ff
color15  #f8fbff
