cursor #e8e0e8
cursor_text_color #cdc4ce

foreground            #e8e0e8
background            #151217
selection_foreground  #372c3f
selection_background  #d1c1d9
url_color             #ddb9f8

color0   #151217
color1   #ff728a
color2   #7cf899
color3   #ffdb72
color4   #cca3eb
color5   #5b3d72
color6   #ddb9f8
color7   #f8efff
color8   #9b95a1
color9   #ff9faf
color10  #a5ffbb
color11  #ffe8a5
color12  #e7c7ff
color13  #ebd1ff
color14  #f2e1ff
color15  #fcf8ff
